add logic for create chat list
Vel217/app_v pull request #11
Opened 2023-03-06 15:03 UTC by Vel217

2023-03-06 15:28 UTC, VladaBelopolskaya requested changes

2023-03-06 15:28 UTC, VladaBelopolskaya commented on src/api/chat-api.js
> +  const url = `${host}/chats?limit=5`;
почему limit = 5 ?

2023-03-06 15:28 UTC, VladaBelopolskaya commented on src/components/Aside/components/ChatInstance.jsx
> +        <p className={classes.dataTime}>{id}</p>
Почему ты это удалила?

2023-03-06 15:28 UTC, VladaBelopolskaya commented on src/components/Aside/components/Chats.jsx
> +    console.log("id", id);
console.log

2023-03-06 15:28 UTC, VladaBelopolskaya commented on src/components/Aside/components/Chats.jsx
> +    navigate("/chat/start");
тебе надо прокидывать id в url, что бы потом на странице настроек как раз доставать его из url

2023-03-06 15:28 UTC, VladaBelopolskaya commented on src/components/MyContext.jsx
> +import { createContext } from "vm";
не нужен тебе этот файл сейчас

2023-03-06 16:26 UTC, Vel217 commented on src/api/chat-api.js
> +  const url = `${host}/chats?limit=5`;
решила попробовать как это работает и забыла убрать)

2023-03-06 16:30 UTC, Vel217 commented on src/components/Aside/components/Chats.jsx
> +    navigate("/chat/start");
const handleClick = (id) => {
    navigate(`/chat/start/${id}`);
  };

2023-03-06 16:31 UTC, Vel217 commented on src/components/MyContext.jsx
> +import { createContext } from "vm";
delete)

2023-03-10 10:11 UTC, VladaBelopolskaya commented on src/components/Aside/components/Chats.jsx
> +            key={e}
лучше ключом использовать item.id

2023-03-10 10:11 UTC, VladaBelopolskaya commented on src/components/Aside/components/Chats.jsx
> +        <div style={{ border: isActive === item.id ? "3px dotted red" : null }}>
давай не будем делать инлайновые стили. создай отдельный класс для активного чата. 
так же изменение стилей лучше делать внутри компонента ChatInstance

2023-03-10 11:18 UTC, merged